### ISSUE TITLE
This item does not exist

### ISSUE THREAD

**Issue by gkjpettet** [UBogun/OSXLib#34]
I am unable to compile the macLib project. Running macOS 10.12.5 and Xojo 2017 1.1.

I get the following error after resolving all file path dependencies:

```
AppleBlock.CreateBlock, line 2:
This item does not exist
mid = ObjCBlocks.CreateBlock(BlockAddress)

AppleBlock.ReleaseBlock, line 3:
This item does not exist
ObjCBlocks.ReleaseBlock(mid)
```

How to I fix this?

**Comment by UBogun** [comment]
See the readme: You need Joe’s ObjC blocks plugin to run macLib. And please don’t use the latest commit but the latest release – I still could not fix the external code issues. If you ant a recent version, I can send it to you as a zip file an request.
